version: 1.0.{build}
os: Windows Server 2012 R2

install:
- ps: '& ./scripts/appveyor/install.ps1'

before_build:
- ps: '& ./scripts/appveyor/before_build.ps1'

build:
  project: vipr-t4templatewriter.sln
  verbosity: minimal

test_script:
- ps: '& ./scripts/appveyor/test.ps1'
